<a href="https://colab.research.google.com/github/Utsav-J/DataScienceNotebook/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a.shape)
np.eye(3)

(3,)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 2D

In [ ]:
a = np.arange(20)
a_2d = a.reshape(4,5)
print(a_2d)
print(a_2d.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [ ]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.full((2,2), 3)

array([[3, 3],
       [3, 3]])

In [ ]:
np.random.rand(2,2,2)

array([[[0.66973755, 0.18521806],
        [0.96708456, 0.62752475]],

       [[0.85968951, 0.49222345],
        [0.75363489, 0.36499854]]])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
b = np.zeros_like(a_2d)
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
