<a href="https://colab.research.google.com/github/Utsav-J/DataScienceNotebook/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a.shape)
np.eye(3)

(3,)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 2D

In [ ]:
a = np.arange(20)
a_2d = a.reshape(4,5)
print(a_2d)
print(a_2d.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)


In [ ]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
np.full((2,2), 3)

array([[3, 3],
       [3, 3]])

In [ ]:
np.random.rand(2,2,2)

array([[[0.66973755, 0.18521806],
        [0.96708456, 0.62752475]],

       [[0.85968951, 0.49222345],
        [0.75363489, 0.36499854]]])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
b = np.zeros_like(a_2d)
print(b)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# Flattening

In [30]:
arr = np.arange(20).reshape(4,5)

In [31]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [32]:
print(arr.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# Indexing Slicing

In [3]:
arr = np.arange(20).reshape(4,5)

In [4]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [8]:
a1 = arr[2:,2:]
print(a1)

[[12 13 14]
 [17 18 19]]


In [10]:
a2 = arr[1:3,1:3]
a2

array([[ 6,  7],
       [11, 12]])

# Iterating

In [12]:
for i in np.nditer(arr):
  print(i,end=" ")


0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [13]:
for row in arr:
  for col in row:
    print(col, end= ' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

# Copying

In [15]:
arr_copy = np.copy(arr)
print(arr)

arr_empty = np.empty_like(arr)
print(arr_empty)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[418320712         0         0         0         0]
 [        0         0         0         0         0]
 [        0         0         0         0         0]
 [        0         0         0         0         0]]


In [16]:
arr[1,2] = 10
print(arr)
print(arr_copy)

[[ 0  1  2  3  4]
 [ 5  6 10  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


# Identity

In [20]:
print(np.identity(5, dtype = int))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [29]:
print(np.eye(4,5,-1,dtype = int))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]


In [28]:
print(np.eye(4,4,0,dtype = int))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
